---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
    config_file: config/rubocop.yml
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.slim"
  - "**.coffee"
exclude_paths:
- config/
- db/
- spec/
